import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "w-full h-full overscroll-y-none")}>
        <div className="flex justify-between">
          <p>Logo</p>
          <p>Search</p>
          <p>Dunno</p>
        </div>
        {children}
      </body>
    </html>
  );
}
